### ISSUE TITLE
Πρόβλημα με το frontend build

### ISSUE THREAD

**Issue by spyrosjevan** [scify/Mentorship-matching-backend#1]
Καλησπέρα θα ήθελα ρωτήσω για το παρακάτω πρόβλημα.

Προσπαθώ κανονικά να κατεβάσω τα dependancies για το frontend build με  `npm install` αλλά παίρνω τα παρακάτω errors

![untitled-1](https://user-images.githubusercontent.com/17203716/47961899-2c324c00-e01c-11e8-8195-ff866a67a809.jpg)
![untitled-2](https://user-images.githubusercontent.com/17203716/47961900-2c324c00-e01c-11e8-99cf-9b0fb5676051.jpg)
![untitled-3](https://user-images.githubusercontent.com/17203716/47961901-2c324c00-e01c-11e8-978b-1674c28e8e53.jpg)

Είναι απαραίτητα τα παραπάνω dependencies για τιν λειτουργεία του project;

**Comment by AlexJoom** [comment]
Καλησπέρα spyrosjevan

ναι ειναι απαραίτητο να ολοκληρωθεί μιας και ολα τα dependencies κατεβαίνουν μέσω nmp και γινονται bundle μέσω gulp.
Δυστυχώς παρότι σε Ubuntu ολοκληρώνεται επιτυχώς σε windows environment με Node  10.13.0 LTS εμφανίζει το ίδιο error και σε μένα

Θα πρότεινα να ακολουθήσεις τα βήματα που γράφει στο error  1) Install .net 2.0 framework 2) install visual studio 2015
Μαλλον κάποιο library χρησιμοποιείται απο τα παραπάνω απο το Node κατα τη διάρκεια του npm installation.

Kοιτώντας τα σχετικά issues που εχουν ανοίξει
 https://github.com/sass/node-sass/issues/2074
https://stackoverflow.com/questions/41695251/c-microsoft-cpp-default-props-was-not-found

Πιθανές λύσεις ειναι να
- κάνεις downgrade σε προηγούμενα versions του Node 8.12.0 (απο εδώ) https://nodejs.org/dist/latest-v8.x/ η σε Node 6.

Ή
-  να τρέξεις τις εντολές
`npm install node-sass -g'
 `npm install -g windows-build-tools`

**Comment by AlexJoom** [comment]
@spyrosjevan κοιτώντας ξανά το πρόβλημα πιο αναλυτικά.
Οταν δημιουργηθηκε το project το gulp χρησιμοποιούσε την έκδοση  node  6.14.4.
Βλέπω οτι νέες εκδόσεις σπάνε το gulp. Οπότε στη πράξη πρέπει να γίνει update to gulp στο project ή να χρησιμοποιηθεί η έκδοση 6.14.4 του Node
Μιας και δεν ειναι στο πλάνο να γίνει άμεσα update το project απο εμάς, παραθέτω μια λύση παρακάτω που δοκίμασα σε windows 10 και λειτουργεί:

Εγκατάσταση σε Windows 10 τoυ [Linux Bash Shell](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/)

Απο τη στιγμή που το ενεργοποιήσεις/εγκαταστήσεις ανοίγεις τo bash

![image](https://user-images.githubusercontent.com/3759333/47967501-aa1b4500-e066-11e8-991f-405eaca93dde.png)

πάς στο φακελο του project (οι σκληροί δίσκοι θα ειναι στη τοποθεσία /mnt/)
πχ
` cd /mnt/c/Users/ALX/Git/Mentroship-backend`
και σβήνεις το φάκελο node-modules (αν υπάρχει) μιας και θα τον ξαναδημιουργήσουμε

` rm -rf  node-modules/`

στη συνέχεια εγκαθιστάς την node  6.14.4 (μέσω του nvm):
`sudo apt-get install nvm`
`nvm install 6.14.4`
`nvm use 6.14.4`
και τέλος κάνεις 
`npm install`
και 
`npm run dev` για να παρακολουθεί αλλαγές στα αρχεία και να κάνει ξανά bundle.

![image](https://user-images.githubusercontent.com/3759333/47967847-abe70780-e06a-11e8-87ac-6669dec4d304.png)
![image](https://user-images.githubusercontent.com/3759333/47967849-b7d2c980-e06a-11e8-846b-74c80d6f9f26.png)
